from __future__ import annotations

from pathlib import Path


RAG_STORAGE_ROOT = Path("app/storage/rag")
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
RERANKER_MODEL_NAME = "Xenova/ms-marco-MiniLM-L-6-v2"

EMBEDDING_BATCH_SIZE = 64
VECTOR_SEARCH_LIMIT = 12
RERANK_LIMIT = 5
MIN_RETRIEVAL_SCORE = 0.0

CHUNK_SIZE = 800
CHUNK_OVERLAP = 100
MAX_ROW_BATCH_DOCUMENTS = 24
ROWS_PER_BATCH_DOCUMENT = 25
MAX_COLUMNS_PER_ROW_DOCUMENT = 12
MAX_CONTEXT_CHARS = 7000
